version: '3.8'
services:
  mongodb:
    image: mongo:8.2
    container_name: mongodb_dev
    hostname: localhost
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongodb_dev_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: biblioteca

volumes:
  mongodb_dev_data: